### ISSUE TITLE
Export for volume curves

### ISSUE THREAD

**Issue by morevnaproject** [szaszak/blender_velvets#10]
The plugin doesn't export volume curves of sound strips.

Sometimes I do basic volume effects in Blender (fades in/out) and then export to Ardour. It would be really helpful to have volume curves exported as well.

**Comment by szaszak** [comment]
Hi, sorry for the very late reply. It would be very convenient indeed to export the volume faders. Unfortunately, since Ardour does not have an API and Blue Velvet has to basically re-create an XML project from zero, rebuilding the faders would be too much work. I'll take it as a feature request (one that I myself would love to have) but to implement it would require some time. If the time window opens, I'll see what I can do.
