### ISSUE TITLE
.ardour Import Plug-In

### ISSUE THREAD

**Issue by libreartist** [szaszak/blender_velvets#15]
Just like there is an export plugin for Ardour, can you make an import-to-VSE plugin as well, retaining the cuts (I request this because I am zero in software development)? Because, I would like to have workarounds, and it is best if we do the final video render from VSE only once.

Blender Audio --> Ardour Audio (without MIDI & instruments info) --> Blender Video.

Thank you  :-)
I'm a huge beneficiary of your work already.

**Comment by szaszak** [comment]
Hi libreartist,

Sorry for the late response. Unfortunatelly, it'd be difficult to code an inverse addon such as an exporter from Ardour back to Blender. This is because Ardour doesn't have an API and mostly everything you'd use in Ardour (effects, fades etc) wouldn't be readable by Blender's internal sound management. What you can do, however, is do all audio treatment in Ardour and export the final sound version back to Blender as a stereo/surround audio track - this would be perfectly readable by the VSE. So the process would be: (a) do all the editing in Blender and export audio tracks with the addon; (b) do all audio treatment in Ardour and export the final audio; (c) export the final video + final audio in Blender VSE. For this you'd mute the previous (pre-ardour) audio tracks in Blender VSE and use only the ones you've imported after Ardour. Does it make sense? 

best,

**Comment by tin2tin** [comment]
Unfortunately, there is next to none interest on the Ardour side of things to add importers or exporters.

Hopefully one day all open source a/v projects will use the same format as an  import/export hub like this one: https://github.com/PixarAnimationStudios/OpenTimelineIO

**Comment by libreartist** [comment]
Thank you, szaszak! I'm grateful to ur tip. I, too, am looking forward to how open source community adopts OpenTimelineIO, like tin2tin said. Bear this artist's curiousity, I wonder if there's any possibility for Blender's plugin that could parse and open Ardour's XML files (without MIDI info, which is unwanted for Blender's case)?

I thank you once again :-)

**Comment by szaszak** [comment]
I'd would be able to read the XML and 'translate' the audio cuts in a way the Blender VSE would recognize - so you'd have basically what is shown today in Ardour coming from Blender via the addon. 

If the audio is stereo, chances are it'd also be possible to translate the left/right information from Ardour to Blender's panning info. With some effort, the info on fade ins and outs could also be translated and read by Blender's VSE. Note that I haven't done this for the addon for the opposite direction (export Blender > Ardour) because it seemed too much hassle at the time and I was afraid it would add complexity in the maintenance of the addon for little gain, even though particularly I feel it is a desireable feature.

All the other info, at least from what I know at this moment, would be lost - this includes any effects you might have applied in Ardour (such as a simple gain, for example, or a normalize), basically because you don't have these features inside Blender. So the limitation here is not exactly in what can be done by Ardour and therefore present at it's XML, but what can be read by Blender.

Hope it helps.

**Comment by libreartist** [comment]
Thank you! Yes, your dedicated answers really help me in understanding the complexity. I am one of the million beneficiaries of your work. I despise, Ibcan't contribute for efforts like this right now, but, I hope, I will be of some help to people like you in future.
Thank you :-)
