### ISSUE TITLE
Power Sequencer merger?

### ISSUE THREAD

**Issue by libreartist** [szaszak/blender_velvets#17]
Hi! While we are counting on what Blender 2.8's new python API has to offer for plugin development, and the update of 2.8's VSE is still under speculation, I've heard of a project called Blender Power Sequencer (https://github.com/GDquest/Blender-power-sequencer/), and I've started using it. It gives almost the same capability I get from using the Blender Velvets, yet both set of plugins are somewhat distinct in certain areas, which I found intriguing, what if both projects could merge and possibly benefit the community? I found the maintainer of Blender Power Sequencer project, @NathanLovato to be friendly and responsive. Thank you.

**Comment by NathanLovato** [comment]
Actually before I started power sequencer, we were briefly in touch with szaszak. I wanted to work on velvets instead of reinventing the wheel, but the lad was quite busy.

**Comment by libreartist** [comment]
Well, the wish was for the sake of Blender :-)

**Comment by NathanLovato** [comment]
You can't merge add-ons, as I explained on the other post. You can port relevant tools from one to another, changing the UX along the way... but that's as much work as writing tools from scratch most of the time. I guess you don't have a lot of programming experience, am I right? It might sound nice on paper, but it's really not worth it. 

And it doesn't affect Blender's development either. The one thing that could affect it directly and in a substantial way is money: funding work on the VSE, having a professional focus on it for some time. Otherwise a lot of communication (getting thousands of new users on board, if not tens of thousands), hoping to get 2-3 contributors among them, and luck: waiting for a passionate developer to decide to maintain it.

**Comment by szaszak** [comment]
> Actually before I started power sequencer, we were briefly in touch with szaszak. I wanted to work on velvets instead of reinventing the wheel, but the lad was quite busy.

Yes, what Nathan says is true, in both ways. I wrote the Velvets to have some fun, but since I'm an activist myself and currently working with active mobility issues in my city, which takes a lot of time and effort for trying to achieve some policy changes, I coded them in a way it would suit me (and hopefully other people too), that they'd have low maintenance, and even so that they would still survive smoothly through time. I was a very conscious decision back then due to the fact that, as Nathan put it, the lad is busy and has to earn some living. =)  Being busy shouldn't mean in this case that the addons could not still be useful along time, so I always update them according to the new Blender release. 

I did take a look at the other post and saw Nathan's work, and it is so awesome. It looks great and the documentation is great - and I guess there is no better compliment to one's work than seeing another approach to the same issue and also seeing that this approach has very interesting and new insights. Thanks for that. I'll start to recommend them also for people that write to me.

So, to the second part of what Nathan says that is true. It'd be a great idea to merge the addons, even if picking the things you link most in one and the other, and sort of 'curating' for this section. It is some work on itself though. You could even merge them (everything is possible, really). But once again, it is a work on itself, and by doing so the best would be to have and interested engaged community to take care of it over time, otherwise it'd probably kill the addons on the long run. And finding (or being) these mantainers is not so trivial. =)  

You guys came from Vegas, Resolve etc, so you have different backgrounds and it's great as to how much it adds to the mix. I came from Cinelerra because I wanted not to use those tools. Actually I was really surprised when someone told me how Final Cut would store your EDL after you finished the work, cutting the videos with like 2 seconds before/after them so that they'd take less disk space. Surprised because it seemed like a great idea and also because it could be implemented in Blender (I believe the code for it is in a Velvet's branch). What I mean to say is - if you think it can be done, well, this is a very good first step. It is only by giving a fresh look over things that something new can sprout.

The only thing to bear in mind - the addons operate in another level than the Blender core development. It is a bit like this: Blender tinkers and codes and gives us a very open VSE that allows us to access it, in this case, with the addons. So what they do there is the basis for what we do here, not otherwise. I'd be awesome to be able to code the core of the VSE and to be frank I'd love to, but I can honestly and humbly say that I lack the competence to doing such thing. And that's the beauty of it, really. We can admire their work and build upon it so that both things can coexist. 

One thing that could be done though - and you guys are in better positions that I'd be, coming from the background that you have -, is maybe initiate talks with Blender Foundation. Provide feedback on how you have been using the VSE, even submiting the code as an official Blender addon. Seeing what exactly it is that they see should be updated in the VSE, and how, and how you've been using it. Say, an interview with Ton, just to talk about this issue, understand it. This can help a lot because communications (especially coming from community) can help engaging people and start a movement. Here, we use Blender's VSE for activist groups, people that want a deep and reliable tool for editing their videos, sometimes on the road because some human rights threat is happening elsewhere. So it's not 'professional' in the sense Blender would understand it - it's more humanitarian. Even so, many people prefer to use proprietary tools illegally just because 'the market uses them', so that's why I say your background counts more than mine. 

Well, best for you guys. Cheers.

**Comment by NathanLovato** [comment]
Que legal falar contigo de novo 🙂

> Provide feedback on how you have been using the VSE, even submitting the code as an official Blender addon

That was the goal, I asked 2-3 times about that, but nobody answered. When I'm back in Europe next year I'm looking to go hang out at the Blender foundation, shoot a video there (then visit the Krita devs as well if they have time). With more contributors and hopefully a maintainer someday things could improve but for now...

In the meantime, I'll keep working on the occasional tutorial and tools to hopefully get more users onboard.

**Comment by AndreaMonzini** [comment]
A merge could be very useful !
In particular i find very interesting "Blue Velvet" with the Ardour DAW integration.

It  would be interesting also to edit audio at subframe level in Blender.
And of course i would see better color correction / color grading tools,  in fact "color balance" seems not compatible with "Filmic".
But all these improvement are not possible with simple add-ons so i hope we will see more Blender VSE and compositing improvement after official release of 2.8 maybe with a special code quest?

Anyway @szaszak  and @NathanLovato thank you for your work!
