### ISSUE TITLE
A bit of feedback on Velvet Revolver

### ISSUE THREAD

**Issue by tin2tin** [szaszak/blender_velvets#22]
I've been looking into the Blender built-in proxy creation and playback and came to the conclusion that it is deeply flawed: https://developer.blender.org/T70415

So I was very happy to find your Velvet Revolver add-on which proves that just swapping the files results in a much better performance and playback rate, than the built-in proxy solution. 

I hope it is ok with a bit of feedback?   

If you add -hwaccel auto before the filename and -tune fastdecode to the ffmpeg 4.264 commandline it'll produce files which are much faster encoded and will have a much faster playback in Blender. On my low spec computer -tune fastdecode will let a HD 29.97 fps clip play at an accurate framerate, if Show Cache is switched off, Blend mode is set to Cross and the Output Resolution set to match the footage, using this command line to encode the proxy file:
`ffmpeg.exe -hwaccel auto -i "filename" -pix_fmt yuv420p -g 1 -sn -an -vf colormatrix=bt601:bt709 -c:v libx264 -crf 25 -preset ultrafast -tune fastdecode -threads 0 "output"`

If you want to add a process indicator this might work: https://blog.michelanders.nl/2017/04/how-to-add-progress-indicator-to-the-info-header-in-blender.html
Or this built-in class might be usable: https://developer.blender.org/diffusion/B/browse/master/release/scripts/modules/bpy_extras/wm_utils/progress_report.py

Maybe a proxy checkbox added to the header of the preview could ease the usage for the users?
And when switching the output resolution could be automatically changed to fit the current footage resolution, to avoid the performance loss of Blender internally resizing the footage.

**Comment by szaszak** [comment]
Hi @tin2tin those are all great feedback! Yes, this is the reason why the Velvet Revolver was created - also because Blender doesn't handle well videos with different FPS together in the VSE.

I tested "-hwaccel auto" here and found no improvement in performance. What the Revolver does is encode the videos multithread by default, so that may explain. I tried putting different formats, fps, lenghts and resolutions altogether to see if there was gain and it seems pretty much the same performance. Do you want to double check in your system?

About "-tune fastdecode", this is specific to h264 encoding right? I'm still updating the velvets for Blender 2.80 so I haven't tried switching cache off but in previous versions it was the setting of the output resolution to match the videos' resolution that would have major impact in playback. In your experience you feel fastdecode increases playback fps for h264? I can add it, no worries.

For the Blender 2.80 version I let the "create proxies" enabled by default, because the lack of a default option seemed to be confusing users. Your suggestions are excellent and I hope to have time to check them out, but just to make sure - would you be able to add them to the code as a commit? Process indicator + an easy-to-spot toggle checkbox for proxies would be great additions to have!

best,

**Comment by tin2tin** [comment]
"-hwaccel auto" is hardware and codec dependent: https://trac.ffmpeg.org/wiki/HWAccelIntro 
A bit on "-tune fastdecode" here: https://stackoverflow.com/questions/20963042/encoding-for-fastest-decoding-with-ffmpeg
I'm not much of a coder, but I'm excellent at copy + pasting stuff. So your add-on will be better if you do it yourself, but if you do not have the time, I may try to tinker with it.  :-)  
The only script I know of with detecting and parsing the command line outputs is this one I updated to 2.80, but it is not my script: https://github.com/tin2tin/ktba/blob/master/scripts/addons/parallel_render.py

Whit all your knowlege of the VSE, you may have an interest in joining the VSE chat where people with an interest in improving the VSE discuss the future of it and try to improve it with patches: https://blender.chat/channel/vse

**Comment by tin2tin** [comment]
This may be a better example of a custom progress bar: https://blender.stackexchange.com/a/144212/37272

From a panel in the Text Editor buttons will be inserted to create a progress bar in the info header(which is closed by default in the Scripting workspace). 

```
import bpy
import time

class ProgressWidget(object):
    update_every = 0.2 # seconds

    widget_visible = False
    last_updated = 0

    @staticmethod
    def update_widget(context, force=False):
        sec_since_update = time.time() - ProgressWidget.last_updated

        if not force and sec_since_update < ProgressWidget.update_every:
            return

        # Update the top header        
        for area in bpy.context.screen.areas:
            if area.type == 'INFO':
                area.tag_redraw()

        ProgressWidget.last_updated = time.time()

    @staticmethod
    def draw(self, context):    
        if ProgressWidget.get_progress(context) < 100:

            # Shows the custom progress property as a "bar"
            self.layout.prop(context.scene, "ProgressWidget_progress", text="Progress", slider=True)

        else:
            ProgressWidget.hide()

    @staticmethod
    def create_progress_property():
        bpy.types.Scene.ProgressWidget_progress = bpy.props.IntProperty(default=0, min=0, max=100, step=1, subtype='PERCENTAGE')    

    @staticmethod
    def set_progress(context, value):
        if ProgressWidget.widget_visible:
            context.scene.ProgressWidget_progress = value

    @staticmethod
    def get_progress(context):
        if ProgressWidget.widget_visible:
            return context.scene.ProgressWidget_progress    
        else:
            return 0

    @staticmethod
    def show(context):    
        if not ProgressWidget.widget_visible:
            ProgressWidget.create_progress_property()

            bpy.app.handlers.depsgraph_update_pre.append(ProgressWidget.update_widget)
            bpy.types.INFO_HT_header.append(ProgressWidget.draw)

            ProgressWidget.widget_visible = True

            ProgressWidget.set_progress(context, 0)

    @staticmethod
    def hide():    
        bpy.types.INFO_HT_header.remove(ProgressWidget.draw)
        bpy.app.handlers.depsgraph_update_pre.remove(ProgressWidget.update_widget)

        ProgressWidget.widget_visible = False


# Creates a widget simulator in the text editor side panel
# The code below is only used for widget development

class CUSTOM_PT_testPanel(bpy.types.Panel):
    """Adds a custom panel to the TEXT_EDITOR"""
    bl_idname = 'TEXT_PT_testPanel'
    bl_space_type = "TEXT_EDITOR"
    bl_region_type = "UI"
    bl_label = "Progress Simulator"

    def draw(self, context):
        self.layout.operator("custom.show_progress_widget")
        self.layout.operator("custom.make_progress")


class CUSTOM_OT_show_progress_widget(bpy.types.Operator):
    bl_idname = "custom.show_progress_widget"
    bl_label="Show Widget in Header"

    def execute(self, context):

        ProgressWidget.show(context) # Call this to start showing progress

        return {'FINISHED'}  

class CUSTOM_OT_make_progress(bpy.types.Operator):
    bl_idname = "custom.make_progress"
    bl_label="Make progress"

    def execute(self, context):
        new_progress_value = (ProgressWidget.get_progress(context) + 25) % 125

        # This line will update the progress widget
        # call it from your long-running modal operator (0-100)
        # When progress is 100 or more, the widget disappears
        ProgressWidget.set_progress(context, new_progress_value)

        return {'FINISHED'}

def register():
    bpy.utils.register_class(CUSTOM_PT_testPanel)
    bpy.utils.register_class(CUSTOM_OT_show_progress_widget)
    bpy.utils.register_class(CUSTOM_OT_make_progress)


def unregister():
    bpy.utils.unregister_class(CUSTOM_PT_testPanel)
    bpy.utils.unregister_class(CUSTOM_OT_show_progress_widget)
    bpy.utils.unregister_class(CUSTOM_OT_make_progress)


if __name__ == "__main__":
    register()

    # test call
    bpy.ops.custom.make_progress()

```

**Comment by szaszak** [comment]
Ok, so: 

"-hwaccel auto" added for every encoding made with Velver Revolver;
"-tune fastdecode" added for proxy encoding with h264; and

Due to changes in Blender 2.79 to 2.80 a progress bar seems to be tricky. @ideasman42  however provided an ellegant and quick solution [here](https://blender.stackexchange.com/questions/3219/how-to-show-to-the-user-a-progression-in-a-script/3285) that was easy to implement. This is not exactly a progress "bar" but a counter in the mouse pointer - once you hit the button to encode the files, the pointer becomes a counter that goes from 0 to 100% to everyone can track progress within Blender's interface.

The suggestion regarding the proxy checkbox is easy to implement but needs some thought on because things can get confusing quickly, so I need to think this over.
